/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;

namespace PEIMSV3Cs
{
	public partial class frmDisease : Form
	{
		private MySqlDataAdapter ad;
		
		public frmDisease()
		{
			InitializeComponent();
		}
		
		private void frmdisease_Load(object sender, EventArgs e)
		{
			string strConn = "server=localhost;user id=root;database=pharma;password=;";
			ad = new MySqlDataAdapter("select * from `disease`", strConn);
			MySqlCommandBuilder builder = new MySqlCommandBuilder(ad);
			ad.Fill(this.newDataSet.disease);
			ad.DeleteCommand = builder.GetDeleteCommand();
			ad.UpdateCommand = builder.GetUpdateCommand();
			ad.InsertCommand = builder.GetInsertCommand();
			MySqlDataAdapter ad3;
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			diseaseBindingSource.EndEdit();
			ad.Update(this.newDataSet.disease);
			
		}
		
		private void frmdisease_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void diseaseIDTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( diseaseIDTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( diseaseIDTextBox, "The field diseaseID is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( diseaseIDTextBox, "" ); } 
		}
		
		private void nameTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( nameTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( nameTextBox, "The field name is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( nameTextBox, "" ); } 
		}
		
		private void productIDTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( productIDTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( productIDTextBox, "The field productID is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( productIDTextBox, "" ); } 
		}
		
		private void requirementProductTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( requirementProductTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( requirementProductTextBox, "The field requirementProduct is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( requirementProductTextBox, "" ); } 
		}
		
		private void agesAffectedTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( agesAffectedTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( agesAffectedTextBox, "The field agesAffected is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( agesAffectedTextBox, "" ); } 
		}
		
		private void typeTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( typeTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( typeTextBox, "The field type is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( typeTextBox, "" ); } 
		}
		
		private void spreadingRatePerWkTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( spreadingRatePerWkTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( spreadingRatePerWkTextBox, "The field spreadingRatePerWk is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( spreadingRatePerWkTextBox, "" ); } 
		}

		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			diseaseBindingSource.AddNew();
		}

        private void AddButton_Click(object sender, EventArgs e)
        {
            diseaseBindingSource.AddNew();
        }

        private void DeleteButton_Click(object sender, EventArgs e)
        {
            diseaseBindingSource.RemoveCurrent();
            MessageBox.Show("Please save the following changes");
        }

        private void UpdateButton_Click(object sender, EventArgs e)
        {
            if (!this.Validate()) return;
            diseaseBindingSource.EndEdit();
            ad.Update(this.newDataSet.disease);
            MessageBox.Show("Record updated successfully");
        }

        private void SaveButton_Click(object sender, EventArgs e)
        {
            if (!this.Validate()) return;
            diseaseBindingSource.EndEdit();
            ad.Update(this.newDataSet.disease);
            MessageBox.Show("Record saved successfully");
        }

        private void ExitButton_Click(object sender, EventArgs e)
        {
            this.Hide();
        }
	}
}
