/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

namespace PEIMSV3Cs
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip = new System.Windows.Forms.MenuStrip();
            this.menuToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.quickLinksToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.authorizarionAuthenticationProfilesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.cRMToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.orderDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.orderFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.orderReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.invoiceDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.invoiceFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.invoiceReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.customerDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.customerFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.customerReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.inventoryManagementToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.productDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.productFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.productReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.inventoryItemDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.inventoryItemFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.inventoryItemReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.rFIDTagDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.rFIDTagFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.rFIDTagReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.serviceManagementToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.sMSClientToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.shippingFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.shippingReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.emailClientToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.locationFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.locationReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.productPlanningToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.productConsumptionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.productConsumptionFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.productConsumptionReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.diseaseDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.diseaseFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.diseaseReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.countryDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.countryFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.contryReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.casesDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.casesFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.casesReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.categoryDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.categoryFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.categoryReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.hRMToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.employeeDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.employeeFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.employeeReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.departmentDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.departmentFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.departmentReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.payrollDetailsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.payrollFormToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.payrollReportToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutPEIMSToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip
            // 
            this.menuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.menuToolStripMenuItem,
            this.cRMToolStripMenuItem,
            this.inventoryManagementToolStripMenuItem,
            this.serviceManagementToolStripMenuItem,
            this.productPlanningToolStripMenuItem,
            this.hRMToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.menuStrip.Location = new System.Drawing.Point(0, 0);
            this.menuStrip.Name = "menuStrip";
            this.menuStrip.Size = new System.Drawing.Size(868, 24);
            this.menuStrip.TabIndex = 2;
            this.menuStrip.Text = "menuStrip2";
            // 
            // menuToolStripMenuItem
            // 
            this.menuToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.quickLinksToolStripMenuItem,
            this.authorizarionAuthenticationProfilesToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.menuToolStripMenuItem.Name = "menuToolStripMenuItem";
            this.menuToolStripMenuItem.Size = new System.Drawing.Size(50, 20);
            this.menuToolStripMenuItem.Text = "Menu";
            // 
            // quickLinksToolStripMenuItem
            // 
            this.quickLinksToolStripMenuItem.Name = "quickLinksToolStripMenuItem";
            this.quickLinksToolStripMenuItem.Size = new System.Drawing.Size(213, 22);
            this.quickLinksToolStripMenuItem.Text = "Quick Links";
            this.quickLinksToolStripMenuItem.Click += new System.EventHandler(this.quickLinksToolStripMenuItem_Click_1);
            // 
            // authorizarionAuthenticationProfilesToolStripMenuItem
            // 
            this.authorizarionAuthenticationProfilesToolStripMenuItem.Name = "authorizarionAuthenticationProfilesToolStripMenuItem";
            this.authorizarionAuthenticationProfilesToolStripMenuItem.Size = new System.Drawing.Size(213, 22);
            this.authorizarionAuthenticationProfilesToolStripMenuItem.Text = "User Account Managment";
            this.authorizarionAuthenticationProfilesToolStripMenuItem.Click += new System.EventHandler(this.authorizarionAuthenticationProfilesToolStripMenuItem_Click);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(213, 22);
            this.exitToolStripMenuItem.Text = "Exit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.exitToolStripMenuItem_Click);
            // 
            // cRMToolStripMenuItem
            // 
            this.cRMToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.orderDetailsToolStripMenuItem,
            this.invoiceDetailsToolStripMenuItem,
            this.customerDetailsToolStripMenuItem});
            this.cRMToolStripMenuItem.Name = "cRMToolStripMenuItem";
            this.cRMToolStripMenuItem.Size = new System.Drawing.Size(45, 20);
            this.cRMToolStripMenuItem.Text = "CRM";
            // 
            // orderDetailsToolStripMenuItem
            // 
            this.orderDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.orderFormToolStripMenuItem,
            this.orderReportToolStripMenuItem});
            this.orderDetailsToolStripMenuItem.Name = "orderDetailsToolStripMenuItem";
            this.orderDetailsToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.orderDetailsToolStripMenuItem.Text = "Order Details";
            // 
            // orderFormToolStripMenuItem
            // 
            this.orderFormToolStripMenuItem.Name = "orderFormToolStripMenuItem";
            this.orderFormToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.orderFormToolStripMenuItem.Text = "Order Form";
            this.orderFormToolStripMenuItem.Click += new System.EventHandler(this.orderFormToolStripMenuItem_Click);
            // 
            // orderReportToolStripMenuItem
            // 
            this.orderReportToolStripMenuItem.Name = "orderReportToolStripMenuItem";
            this.orderReportToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.orderReportToolStripMenuItem.Text = "Order Report";
            this.orderReportToolStripMenuItem.Click += new System.EventHandler(this.orderReportToolStripMenuItem_Click_1);
            // 
            // invoiceDetailsToolStripMenuItem
            // 
            this.invoiceDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.invoiceFormToolStripMenuItem,
            this.invoiceReportToolStripMenuItem});
            this.invoiceDetailsToolStripMenuItem.Name = "invoiceDetailsToolStripMenuItem";
            this.invoiceDetailsToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.invoiceDetailsToolStripMenuItem.Text = "Invoice Details";
            // 
            // invoiceFormToolStripMenuItem
            // 
            this.invoiceFormToolStripMenuItem.Name = "invoiceFormToolStripMenuItem";
            this.invoiceFormToolStripMenuItem.Size = new System.Drawing.Size(150, 22);
            this.invoiceFormToolStripMenuItem.Text = "Invoice Form";
            this.invoiceFormToolStripMenuItem.Click += new System.EventHandler(this.invoiceFormToolStripMenuItem_Click_1);
            // 
            // invoiceReportToolStripMenuItem
            // 
            this.invoiceReportToolStripMenuItem.Name = "invoiceReportToolStripMenuItem";
            this.invoiceReportToolStripMenuItem.Size = new System.Drawing.Size(150, 22);
            this.invoiceReportToolStripMenuItem.Text = "Invoice Report";
            this.invoiceReportToolStripMenuItem.Click += new System.EventHandler(this.invoiceReportToolStripMenuItem_Click_1);
            // 
            // customerDetailsToolStripMenuItem
            // 
            this.customerDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.customerFormToolStripMenuItem,
            this.customerReportToolStripMenuItem});
            this.customerDetailsToolStripMenuItem.Name = "customerDetailsToolStripMenuItem";
            this.customerDetailsToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.customerDetailsToolStripMenuItem.Text = "Customer Details";
            // 
            // customerFormToolStripMenuItem
            // 
            this.customerFormToolStripMenuItem.Name = "customerFormToolStripMenuItem";
            this.customerFormToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.customerFormToolStripMenuItem.Text = "Customer Form";
            this.customerFormToolStripMenuItem.Click += new System.EventHandler(this.customerFormToolStripMenuItem_Click_1);
            // 
            // customerReportToolStripMenuItem
            // 
            this.customerReportToolStripMenuItem.Name = "customerReportToolStripMenuItem";
            this.customerReportToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.customerReportToolStripMenuItem.Text = "Customer Report";
            // 
            // inventoryManagementToolStripMenuItem
            // 
            this.inventoryManagementToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.productDetailsToolStripMenuItem,
            this.inventoryItemDetailsToolStripMenuItem,
            this.rFIDTagDetailsToolStripMenuItem});
            this.inventoryManagementToolStripMenuItem.Name = "inventoryManagementToolStripMenuItem";
            this.inventoryManagementToolStripMenuItem.Size = new System.Drawing.Size(143, 20);
            this.inventoryManagementToolStripMenuItem.Text = "Inventory Management";
            // 
            // productDetailsToolStripMenuItem
            // 
            this.productDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.productFormToolStripMenuItem,
            this.productReportToolStripMenuItem});
            this.productDetailsToolStripMenuItem.Name = "productDetailsToolStripMenuItem";
            this.productDetailsToolStripMenuItem.Size = new System.Drawing.Size(189, 22);
            this.productDetailsToolStripMenuItem.Text = "Product Details";
            // 
            // productFormToolStripMenuItem
            // 
            this.productFormToolStripMenuItem.Name = "productFormToolStripMenuItem";
            this.productFormToolStripMenuItem.Size = new System.Drawing.Size(154, 22);
            this.productFormToolStripMenuItem.Text = "Product Form";
            this.productFormToolStripMenuItem.Click += new System.EventHandler(this.productFormToolStripMenuItem_Click_1);
            // 
            // productReportToolStripMenuItem
            // 
            this.productReportToolStripMenuItem.Name = "productReportToolStripMenuItem";
            this.productReportToolStripMenuItem.Size = new System.Drawing.Size(154, 22);
            this.productReportToolStripMenuItem.Text = "Product Report";
            this.productReportToolStripMenuItem.Click += new System.EventHandler(this.productReportToolStripMenuItem_Click_1);
            // 
            // inventoryItemDetailsToolStripMenuItem
            // 
            this.inventoryItemDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.inventoryItemFormToolStripMenuItem,
            this.inventoryItemReportToolStripMenuItem});
            this.inventoryItemDetailsToolStripMenuItem.Name = "inventoryItemDetailsToolStripMenuItem";
            this.inventoryItemDetailsToolStripMenuItem.Size = new System.Drawing.Size(189, 22);
            this.inventoryItemDetailsToolStripMenuItem.Text = "Inventory Item Details";
            // 
            // inventoryItemFormToolStripMenuItem
            // 
            this.inventoryItemFormToolStripMenuItem.Name = "inventoryItemFormToolStripMenuItem";
            this.inventoryItemFormToolStripMenuItem.Size = new System.Drawing.Size(189, 22);
            this.inventoryItemFormToolStripMenuItem.Text = "Inventory Item Form";
            this.inventoryItemFormToolStripMenuItem.Click += new System.EventHandler(this.inventoryItemFormToolStripMenuItem_Click_1);
            // 
            // inventoryItemReportToolStripMenuItem
            // 
            this.inventoryItemReportToolStripMenuItem.Name = "inventoryItemReportToolStripMenuItem";
            this.inventoryItemReportToolStripMenuItem.Size = new System.Drawing.Size(189, 22);
            this.inventoryItemReportToolStripMenuItem.Text = "Inventory Item Report";
            this.inventoryItemReportToolStripMenuItem.Click += new System.EventHandler(this.inventoryItemReportToolStripMenuItem_Click_1);
            // 
            // rFIDTagDetailsToolStripMenuItem
            // 
            this.rFIDTagDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.rFIDTagFormToolStripMenuItem,
            this.rFIDTagReportToolStripMenuItem});
            this.rFIDTagDetailsToolStripMenuItem.Name = "rFIDTagDetailsToolStripMenuItem";
            this.rFIDTagDetailsToolStripMenuItem.Size = new System.Drawing.Size(189, 22);
            this.rFIDTagDetailsToolStripMenuItem.Text = "RFID Tag Details";
            // 
            // rFIDTagFormToolStripMenuItem
            // 
            this.rFIDTagFormToolStripMenuItem.Name = "rFIDTagFormToolStripMenuItem";
            this.rFIDTagFormToolStripMenuItem.Size = new System.Drawing.Size(159, 22);
            this.rFIDTagFormToolStripMenuItem.Text = "RFID Tag Form";
            this.rFIDTagFormToolStripMenuItem.Click += new System.EventHandler(this.rFIDTagFormToolStripMenuItem_Click_1);
            // 
            // rFIDTagReportToolStripMenuItem
            // 
            this.rFIDTagReportToolStripMenuItem.Name = "rFIDTagReportToolStripMenuItem";
            this.rFIDTagReportToolStripMenuItem.Size = new System.Drawing.Size(159, 22);
            this.rFIDTagReportToolStripMenuItem.Text = "RFID Tag Report";
            this.rFIDTagReportToolStripMenuItem.Click += new System.EventHandler(this.rFIDTagReportToolStripMenuItem_Click_1);
            // 
            // serviceManagementToolStripMenuItem
            // 
            this.serviceManagementToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.sMSClientToolStripMenuItem,
            this.emailClientToolStripMenuItem});
            this.serviceManagementToolStripMenuItem.Name = "serviceManagementToolStripMenuItem";
            this.serviceManagementToolStripMenuItem.Size = new System.Drawing.Size(130, 20);
            this.serviceManagementToolStripMenuItem.Text = "Service Management";
            // 
            // sMSClientToolStripMenuItem
            // 
            this.sMSClientToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.shippingFormToolStripMenuItem,
            this.shippingReportToolStripMenuItem});
            this.sMSClientToolStripMenuItem.Name = "sMSClientToolStripMenuItem";
            this.sMSClientToolStripMenuItem.Size = new System.Drawing.Size(165, 22);
            this.sMSClientToolStripMenuItem.Text = "Shipping Deatails";
            // 
            // shippingFormToolStripMenuItem
            // 
            this.shippingFormToolStripMenuItem.Name = "shippingFormToolStripMenuItem";
            this.shippingFormToolStripMenuItem.Size = new System.Drawing.Size(159, 22);
            this.shippingFormToolStripMenuItem.Text = "Shipping Form";
            this.shippingFormToolStripMenuItem.Click += new System.EventHandler(this.shippingFormToolStripMenuItem_Click_1);
            // 
            // shippingReportToolStripMenuItem
            // 
            this.shippingReportToolStripMenuItem.Name = "shippingReportToolStripMenuItem";
            this.shippingReportToolStripMenuItem.Size = new System.Drawing.Size(159, 22);
            this.shippingReportToolStripMenuItem.Text = "Shipping Report";
            this.shippingReportToolStripMenuItem.Click += new System.EventHandler(this.shippingReportToolStripMenuItem_Click);
            // 
            // emailClientToolStripMenuItem
            // 
            this.emailClientToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.locationFormToolStripMenuItem,
            this.locationReportToolStripMenuItem});
            this.emailClientToolStripMenuItem.Name = "emailClientToolStripMenuItem";
            this.emailClientToolStripMenuItem.Size = new System.Drawing.Size(165, 22);
            this.emailClientToolStripMenuItem.Text = "Location Details";
            // 
            // locationFormToolStripMenuItem
            // 
            this.locationFormToolStripMenuItem.Name = "locationFormToolStripMenuItem";
            this.locationFormToolStripMenuItem.Size = new System.Drawing.Size(158, 22);
            this.locationFormToolStripMenuItem.Text = "Location Form";
            this.locationFormToolStripMenuItem.Click += new System.EventHandler(this.locationFormToolStripMenuItem_Click_1);
            // 
            // locationReportToolStripMenuItem
            // 
            this.locationReportToolStripMenuItem.Name = "locationReportToolStripMenuItem";
            this.locationReportToolStripMenuItem.Size = new System.Drawing.Size(158, 22);
            this.locationReportToolStripMenuItem.Text = "Location Report";
            this.locationReportToolStripMenuItem.Click += new System.EventHandler(this.locationReportToolStripMenuItem_Click_1);
            // 
            // productPlanningToolStripMenuItem
            // 
            this.productPlanningToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.productConsumptionToolStripMenuItem,
            this.diseaseDetailsToolStripMenuItem,
            this.countryDetailsToolStripMenuItem,
            this.casesDetailsToolStripMenuItem,
            this.categoryDetailsToolStripMenuItem});
            this.productPlanningToolStripMenuItem.Name = "productPlanningToolStripMenuItem";
            this.productPlanningToolStripMenuItem.Size = new System.Drawing.Size(111, 20);
            this.productPlanningToolStripMenuItem.Text = "Product Planning";
            // 
            // productConsumptionToolStripMenuItem
            // 
            this.productConsumptionToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.productConsumptionFormToolStripMenuItem,
            this.productConsumptionReportToolStripMenuItem});
            this.productConsumptionToolStripMenuItem.Name = "productConsumptionToolStripMenuItem";
            this.productConsumptionToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.productConsumptionToolStripMenuItem.Text = "Product Consumption Details";
            // 
            // productConsumptionFormToolStripMenuItem
            // 
            this.productConsumptionFormToolStripMenuItem.Name = "productConsumptionFormToolStripMenuItem";
            this.productConsumptionFormToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.productConsumptionFormToolStripMenuItem.Text = "Product Consumption Form";
            this.productConsumptionFormToolStripMenuItem.Click += new System.EventHandler(this.productConsumptionFormToolStripMenuItem_Click_1);
            // 
            // productConsumptionReportToolStripMenuItem
            // 
            this.productConsumptionReportToolStripMenuItem.Name = "productConsumptionReportToolStripMenuItem";
            this.productConsumptionReportToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.productConsumptionReportToolStripMenuItem.Text = "Product Consumption Report";
            this.productConsumptionReportToolStripMenuItem.Click += new System.EventHandler(this.productConsumptionReportToolStripMenuItem_Click_1);
            // 
            // diseaseDetailsToolStripMenuItem
            // 
            this.diseaseDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.diseaseFormToolStripMenuItem,
            this.diseaseReportToolStripMenuItem});
            this.diseaseDetailsToolStripMenuItem.Name = "diseaseDetailsToolStripMenuItem";
            this.diseaseDetailsToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.diseaseDetailsToolStripMenuItem.Text = "Disease Details";
            // 
            // diseaseFormToolStripMenuItem
            // 
            this.diseaseFormToolStripMenuItem.Name = "diseaseFormToolStripMenuItem";
            this.diseaseFormToolStripMenuItem.Size = new System.Drawing.Size(151, 22);
            this.diseaseFormToolStripMenuItem.Text = "Disease Form";
            this.diseaseFormToolStripMenuItem.Click += new System.EventHandler(this.diseaseFormToolStripMenuItem_Click_1);
            // 
            // diseaseReportToolStripMenuItem
            // 
            this.diseaseReportToolStripMenuItem.Name = "diseaseReportToolStripMenuItem";
            this.diseaseReportToolStripMenuItem.Size = new System.Drawing.Size(151, 22);
            this.diseaseReportToolStripMenuItem.Text = "Disease Report";
            this.diseaseReportToolStripMenuItem.Click += new System.EventHandler(this.diseaseReportToolStripMenuItem_Click_1);
            // 
            // countryDetailsToolStripMenuItem
            // 
            this.countryDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.countryFormToolStripMenuItem,
            this.contryReportToolStripMenuItem});
            this.countryDetailsToolStripMenuItem.Name = "countryDetailsToolStripMenuItem";
            this.countryDetailsToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.countryDetailsToolStripMenuItem.Text = "Country Details";
            // 
            // countryFormToolStripMenuItem
            // 
            this.countryFormToolStripMenuItem.Name = "countryFormToolStripMenuItem";
            this.countryFormToolStripMenuItem.Size = new System.Drawing.Size(148, 22);
            this.countryFormToolStripMenuItem.Text = "Country Form";
            this.countryFormToolStripMenuItem.Click += new System.EventHandler(this.countryFormToolStripMenuItem_Click_1);
            // 
            // contryReportToolStripMenuItem
            // 
            this.contryReportToolStripMenuItem.Name = "contryReportToolStripMenuItem";
            this.contryReportToolStripMenuItem.Size = new System.Drawing.Size(148, 22);
            this.contryReportToolStripMenuItem.Text = "Contry Report";
            this.contryReportToolStripMenuItem.Click += new System.EventHandler(this.contryReportToolStripMenuItem_Click_1);
            // 
            // casesDetailsToolStripMenuItem
            // 
            this.casesDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.casesFormToolStripMenuItem,
            this.casesReportToolStripMenuItem});
            this.casesDetailsToolStripMenuItem.Name = "casesDetailsToolStripMenuItem";
            this.casesDetailsToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.casesDetailsToolStripMenuItem.Text = "Cases Details";
            // 
            // casesFormToolStripMenuItem
            // 
            this.casesFormToolStripMenuItem.Name = "casesFormToolStripMenuItem";
            this.casesFormToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.casesFormToolStripMenuItem.Text = "Cases Form";
            this.casesFormToolStripMenuItem.Click += new System.EventHandler(this.casesFormToolStripMenuItem_Click_1);
            // 
            // casesReportToolStripMenuItem
            // 
            this.casesReportToolStripMenuItem.Name = "casesReportToolStripMenuItem";
            this.casesReportToolStripMenuItem.Size = new System.Drawing.Size(142, 22);
            this.casesReportToolStripMenuItem.Text = "Cases Report";
            this.casesReportToolStripMenuItem.Click += new System.EventHandler(this.casesReportToolStripMenuItem_Click_1);
            // 
            // categoryDetailsToolStripMenuItem
            // 
            this.categoryDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.categoryFormToolStripMenuItem,
            this.categoryReportToolStripMenuItem});
            this.categoryDetailsToolStripMenuItem.Name = "categoryDetailsToolStripMenuItem";
            this.categoryDetailsToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.categoryDetailsToolStripMenuItem.Text = "Category Details";
            // 
            // categoryFormToolStripMenuItem
            // 
            this.categoryFormToolStripMenuItem.Name = "categoryFormToolStripMenuItem";
            this.categoryFormToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.categoryFormToolStripMenuItem.Text = "Category form";
            this.categoryFormToolStripMenuItem.Click += new System.EventHandler(this.categoryFormToolStripMenuItem_Click_1);
            // 
            // categoryReportToolStripMenuItem
            // 
            this.categoryReportToolStripMenuItem.Name = "categoryReportToolStripMenuItem";
            this.categoryReportToolStripMenuItem.Size = new System.Drawing.Size(160, 22);
            this.categoryReportToolStripMenuItem.Text = "Category Report";
            this.categoryReportToolStripMenuItem.Click += new System.EventHandler(this.categoryReportToolStripMenuItem_Click_1);
            // 
            // hRMToolStripMenuItem
            // 
            this.hRMToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.employeeDetailsToolStripMenuItem,
            this.departmentDetailsToolStripMenuItem,
            this.payrollDetailsToolStripMenuItem});
            this.hRMToolStripMenuItem.Name = "hRMToolStripMenuItem";
            this.hRMToolStripMenuItem.Size = new System.Drawing.Size(46, 20);
            this.hRMToolStripMenuItem.Text = "HRM";
            // 
            // employeeDetailsToolStripMenuItem
            // 
            this.employeeDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.employeeFormToolStripMenuItem,
            this.employeeReportToolStripMenuItem});
            this.employeeDetailsToolStripMenuItem.Name = "employeeDetailsToolStripMenuItem";
            this.employeeDetailsToolStripMenuItem.Size = new System.Drawing.Size(175, 22);
            this.employeeDetailsToolStripMenuItem.Text = "Employee Details";
            // 
            // employeeFormToolStripMenuItem
            // 
            this.employeeFormToolStripMenuItem.Name = "employeeFormToolStripMenuItem";
            this.employeeFormToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.employeeFormToolStripMenuItem.Text = "Employee Form";
            this.employeeFormToolStripMenuItem.Click += new System.EventHandler(this.employeeFormToolStripMenuItem_Click_1);
            // 
            // employeeReportToolStripMenuItem
            // 
            this.employeeReportToolStripMenuItem.Name = "employeeReportToolStripMenuItem";
            this.employeeReportToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.employeeReportToolStripMenuItem.Text = "Employee Report";
            this.employeeReportToolStripMenuItem.Click += new System.EventHandler(this.employeeReportToolStripMenuItem_Click_1);
            // 
            // departmentDetailsToolStripMenuItem
            // 
            this.departmentDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.departmentFormToolStripMenuItem,
            this.departmentReportToolStripMenuItem});
            this.departmentDetailsToolStripMenuItem.Name = "departmentDetailsToolStripMenuItem";
            this.departmentDetailsToolStripMenuItem.Size = new System.Drawing.Size(175, 22);
            this.departmentDetailsToolStripMenuItem.Text = "Department Details";
            // 
            // departmentFormToolStripMenuItem
            // 
            this.departmentFormToolStripMenuItem.Name = "departmentFormToolStripMenuItem";
            this.departmentFormToolStripMenuItem.Size = new System.Drawing.Size(175, 22);
            this.departmentFormToolStripMenuItem.Text = "Department Form";
            this.departmentFormToolStripMenuItem.Click += new System.EventHandler(this.departmentFormToolStripMenuItem_Click);
            // 
            // departmentReportToolStripMenuItem
            // 
            this.departmentReportToolStripMenuItem.Name = "departmentReportToolStripMenuItem";
            this.departmentReportToolStripMenuItem.Size = new System.Drawing.Size(175, 22);
            this.departmentReportToolStripMenuItem.Text = "Department Report";
            this.departmentReportToolStripMenuItem.Click += new System.EventHandler(this.departmentReportToolStripMenuItem_Click_1);
            // 
            // payrollDetailsToolStripMenuItem
            // 
            this.payrollDetailsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.payrollFormToolStripMenuItem,
            this.payrollReportToolStripMenuItem});
            this.payrollDetailsToolStripMenuItem.Name = "payrollDetailsToolStripMenuItem";
            this.payrollDetailsToolStripMenuItem.Size = new System.Drawing.Size(175, 22);
            this.payrollDetailsToolStripMenuItem.Text = "Payroll Details";
            // 
            // payrollFormToolStripMenuItem
            // 
            this.payrollFormToolStripMenuItem.Name = "payrollFormToolStripMenuItem";
            this.payrollFormToolStripMenuItem.Size = new System.Drawing.Size(148, 22);
            this.payrollFormToolStripMenuItem.Text = "Payroll Form";
            this.payrollFormToolStripMenuItem.Click += new System.EventHandler(this.payrollFormToolStripMenuItem_Click_1);
            // 
            // payrollReportToolStripMenuItem
            // 
            this.payrollReportToolStripMenuItem.Name = "payrollReportToolStripMenuItem";
            this.payrollReportToolStripMenuItem.Size = new System.Drawing.Size(148, 22);
            this.payrollReportToolStripMenuItem.Text = "Payroll Report";
            this.payrollReportToolStripMenuItem.Click += new System.EventHandler(this.payrollReportToolStripMenuItem_Click_1);
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aboutPEIMSToolStripMenuItem,
            this.helpToolStripMenuItem1});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "Help";
            // 
            // aboutPEIMSToolStripMenuItem
            // 
            this.aboutPEIMSToolStripMenuItem.Name = "aboutPEIMSToolStripMenuItem";
            this.aboutPEIMSToolStripMenuItem.Size = new System.Drawing.Size(107, 22);
            this.aboutPEIMSToolStripMenuItem.Text = "About";
            this.aboutPEIMSToolStripMenuItem.Click += new System.EventHandler(this.aboutPEIMSToolStripMenuItem_Click);
            // 
            // helpToolStripMenuItem1
            // 
            this.helpToolStripMenuItem1.Name = "helpToolStripMenuItem1";
            this.helpToolStripMenuItem1.Size = new System.Drawing.Size(107, 22);
            this.helpToolStripMenuItem1.Text = "Help";
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(868, 556);
            this.Controls.Add(this.menuStrip);
            this.IsMdiContainer = true;
            this.Name = "frmMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Main";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.frmMain_Load);
            this.menuStrip.ResumeLayout(false);
            this.menuStrip.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip;
        private System.Windows.Forms.ToolStripMenuItem menuToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem quickLinksToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem cRMToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem orderDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem orderFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem orderReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem invoiceDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem invoiceFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem invoiceReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem customerDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem customerFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem customerReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem inventoryManagementToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem productDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem productFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem productReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem inventoryItemDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem inventoryItemFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem inventoryItemReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem rFIDTagDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem rFIDTagFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem rFIDTagReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem serviceManagementToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem sMSClientToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem shippingFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem shippingReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem emailClientToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem locationFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem locationReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem productPlanningToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem productConsumptionToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem productConsumptionFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem productConsumptionReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem diseaseDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem diseaseFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem diseaseReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem countryDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem countryFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem contryReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem casesDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem casesFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem casesReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem categoryDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem categoryFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem categoryReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem hRMToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem employeeDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem employeeFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem employeeReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem departmentDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem departmentFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem departmentReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem payrollDetailsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem payrollFormToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem payrollReportToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem authorizarionAuthenticationProfilesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutPEIMSToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;


    }
}
